# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLNh3jJzH1UUfPue6o7CzCXok0WUUMZ_
"""

!pip install textblob

from textblob import TextBlob
text = input("Enter a sentence")
blob = TextBlob(text)
score = blob.sentiment.polarity
if score > 0:
  print("positive :)")
elif score < 0:
  print("negative :(")
else :
  print("neutral :|")
print("score",score)